apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-service
  labels:
    app: custom-metrics-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "http"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: custom-metrics-app

